#VM_DEST:=-target 1.4.2
#VM_SOURCE:=-source 1.4

PPFLAGS = -DUSE_JAVA_142

RTJAR = $(shell ./findrtjar.sh)

CLASSPATH = .:$(RTJAR)

JAVAC_OPTS:=$(VM_DEST) $(VM_SOURCE) -O -d $(CLASSDIR) -nowarn -classpath $(CLASSPATH)

#swinggui.class first class file to compile to speed up building
CLASSFILES:=$(CLASSDIR)/swinggui.class $(CLASSFILES)

all: preprocess $(CLASSFILES)

$(CLASSDIR)/%.class: %.java
	@echo "[java -> class] $*"
	@jikes $(JAVAC_OPTS) $<
